#!/usr/bin/env deno run -A
import { dirname } from "https://deno.land/std@0.180.0/path/mod.ts";
const realPath = dirname(Deno.readLinkSync(new URL(import.meta.url).pathname));
const minimg = (await import(realPath + "/minimg.tsx")).default;
minimg();
