#!/usr/bin/env deno run -A
import { dirname } from "https://deno.land/std@0.180.0/path/mod.ts";

const importPath = new URL(import.meta.url).pathname;

// check if importPath is a symlink in Deno
let realPath = "";
if (Deno.lstatSync(importPath).isSymlink) {
  realPath = dirname(Deno.readLinkSync(importPath));
} else {
  realPath = dirname(importPath)
}

// importing automatically starts minimg
await import(realPath + "/minimg.tsx")
